# Example YAML configuration for the staging environment.
# To use this configuration, rename this file from "config.example.yaml" to "config.yaml".
# Fill in the values below with your actual configuration settings. Example values are provided.

# Environment setting
environment: your_environment  # Example: staging

# Server configuration
# Fill in your server port and address
server:
  port: your_server_port  # Example: 8080 
  address: your_production_server_address  # Example: 192.168.1.1 or example.com

# Database configuration
# Fill in your database connection details
db:
  host: your_db_host  # Example: localhost
  port: your_db_port  # Example: 5432
  user: your_db_user  # Example: user
  password: your_db_password  # Example: pass
  name: your_db_name  # Example: mydb

# Redis configuration
# Fill in your Redis connection details
redis:
  addr: your_redis_addr  # Example: localhost:6379
  password: your_redis_password  # Example: ""
  db: your_redis_db  # Example: 0

# JWT configuration
# Fill in your JWT secret
jwt:
  secret: your_jwt_secret  # Example: mysecret
