services:
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: autoban
      POSTGRES_PASSWORD: autoban
      POSTGRES_DB: autoban
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 